comp=g++

comp_flags = -g -Wall

#sol command is for random problems in ATCODER, CODEFORCES, NSES, etc..

sol : temp.cpp
	$(comp) $(comp_flags) temp.cpp

# a-f commands are for full contests in CODEFORCES

a : a.cpp
	$(comp) $(comp_flags) a.cpp

b : b.cpp
	$(comp) $(comp_flags) b.cpp

c : c.cpp
	$(comp) $(comp_flags) c.cpp

d : d.cpp
	$(comp) $(comp_flags) d.cpp

e : e.cpp
	$(comp) $(comp_flags) e.cpp

f : f.cpp
	$(comp) $(comp_flags) f.cpp
